import os
import asyncio
import importlib
from core.config import logger, DYNAMIC_DIR

# =====================================================================
# CATÁLOGO GLOBAL: SYSTEM_TOOLS
# =====================================================================
SYSTEM_TOOLS = {
    "googleWorkspaceAction": {
        "type": "function",
        "function": {
            "name": "googleWorkspaceAction",
            "description": "Interactúa con la suite de Google (Docs, Sheets, Gmail). REQUIERE validación de token.",
            "parameters": {
                "type": "object",
                "properties": {
                    "service": {"type": "string", "enum": ["docs", "sheets", "slides", "gmail", "calendar"]},
                    "action": {"type": "string", "enum": ["create", "open", "list", "sendEmail", "addEvent"]},
                    "params": {"type": "object", "description": "Parámetros específicos (ej. to, subject, title)"}
                },
                "required": ["service", "action"]
            }
        }
    },
    "openMediaApp": {
        "type": "function",
        "function": {
            "name": "openMediaApp",
            "description": "Abre aplicaciones de streaming en modo Kiosco (Chromium aislado).",
            "parameters": {
                "type": "object",
                "properties": {
                    "platform": {"type": "string", "enum": ["spotify", "youtubeMusic", "netflix"]}
                },
                "required": ["platform"]
            }
        }
    },
    "calculateExpression": {
        "type": "function",
        "function": {
            "name": "calculateExpression",
            "description": "Evalúa expresiones aritméticas complejas en el Host.",
            "parameters": {
                "type": "object",
                "properties": {
                    "expression": {"type": "string"}
                },
                "required": ["expression"]
            }
        }
    },
    "setWallpaper": {
        "type": "function",
        "function": {
            "name": "setWallpaper",
            "description": "Cambia el fondo de pantalla del escritorio usando una URL de imagen válida.",
            "parameters": {
                "type": "object",
                "properties": {
                    "imageUrl": {"type": "string"}
                },
                "required": ["imageUrl"]
            }
        }
    },
    "applyCssTheme": {
        "type": "function",
        "function": {
            "name": "applyCssTheme",
            "description": "Aplica un nuevo estilo físico (CSS) a la interfaz de AGNUX. Usa esto cuando el usuario pida cambiar el tema o estilo visual (ej. modo hacker, modo xp, modo dark, estilo cyberpunk).",
            "parameters": {
                "type": "object",
                "properties": {
                    "cssCode": {"type": "string", "description": "Código CSS puro para inyectar globalmente en el sistema. Debe modificar variables CSS como --agnux-bg-color, --agnux-accent o definir estilos de clases globales."}
                },
                "required": ["cssCode"]
            }
        }
    }
}

# =====================================================================
# FUNCIONES AUXILIARES FÍSICAS Y AUTOGÉNESIS
# =====================================================================
async def autogenerar_nueva_tool(nombre_funcion: str, codigo_python: str, descripcion_docstring: str) -> str:
    nombre_limpio = nombre_funcion.strip().lower().replace(" ", "_").replace("-", "_")
    if nombre_limpio.endswith(".py"): nombre_limpio = nombre_limpio.replace(".py", "")
        
    path_archivo = os.path.join(DYNAMIC_DIR, f"{nombre_limpio}.py")

    codigo_depurado = codigo_python.strip()
    if codigo_depurado.startswith("```"):
        codigo_depurado = codigo_depurado.split("```")[1].replace("python", "", 1).strip()

    plantilla_final = (
        f'""\"\nAuto-generated by AGNUX OS. {descripcion_docstring}\n""\"\n\n'
        f'{codigo_depurado}\n'
    )
    
    try:
        with open(path_archivo, "w", encoding="utf-8") as f: f.write(plantilla_final)
        logger.info(f"💾 [AUTOGÉNESIS] Tool instalada asíncronamente en host: {path_archivo}")
        return f"SUCCESS: '{nombre_limpio}' instalada con éxito."
    except Exception as e:
        return f"ERROR KERNEL: Falla crítica en autogénesis: {e}"

async def ejecutar_herramienta_local(nombre: str, argumentos: dict = None, terminal_id: str = None, user_id: str = None) -> str:
    logger.info(f"🔌 [EJECUTOR] Invocando subproceso host: '{nombre}'")
    if argumentos is None: argumentos = {}
    
    # Inyectamos contexto de sistema en los argumentos para que las herramientas generadas
    # puedan acceder a la terminal_id y user_id mediante kwargs
    if terminal_id: argumentos["__terminal_id"] = terminal_id
    if user_id: argumentos["__user_id"] = user_id
    
    if nombre == "autogenerar_nueva_tool":
        return await autogenerar_nueva_tool(**argumentos)
        
    try:
        if os.path.exists(DYNAMIC_DIR):
            for archivo in os.listdir(DYNAMIC_DIR):
                if archivo == f"{nombre}.py":
                    modulo = importlib.import_module(f"dynamic_tools.{nombre}")
                    importlib.reload(modulo)
                    funcion_dinamica = getattr(modulo, nombre)
                    if asyncio.iscoroutinefunction(funcion_dinamica):
                        resultado = await funcion_dinamica(**argumentos) if argumentos else await funcion_dinamica()
                    else:
                        resultado = funcion_dinamica(**argumentos) if argumentos else funcion_dinamica()
                    return str(resultado)
    except Exception as e:
        return f"❌ Falla en herramienta '{nombre}': {e}"
    
    return f"404: Herramienta '{nombre}' no encontrada en el catálogo dinámico ni estático."
