FROM node:18-slim

WORKDIR /app

# Instalar Angular CLI global en el entorno del contenedor
RUN npm install -g @angular/cli@latest

EXPOSE 4200

# Instalamos las dependencias locales al vuelo y luego levantamos Angular
CMD ["sh", "-c", "npm install && ng serve --host 0.0.0.0 --poll 2000 --disable-host-check"]