services:
  # 🧠 CORE BACKEND: API FASTAPI + EMISOR DE EVENTOS SSE (AG-UI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.back
    container_name: agnux_backend_dev
    ports:
      - "8000:8000"
    environment:
      - AGNUX_IA_PROVIDER=local
      - AGNUX_ACTIVE_MODEL=ministral-es:latest  # 🔥 El orquestador principal del SO
      - OLLAMA_HOST=http://10.10.0.48:11434
      - QDRANT_HOST=http://qdrant_db:6333     # 🔌 Enlace interno al bus de Rust de Qdrant
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      # Volumen específico para preservar las automatizaciones que la IA cree o mute en caliente
      - ./backend/dynamic_tools:/app/dynamic_tools
    networks:
      - agnux_net
    depends_on:
      - qdrant_db  # 🛡️ El Kernel espera a que la base vectorial esté en línea
    restart: unless-stopped

  # 🗄️ BASE DE DATOS VECTORIAL: QDRANT (MEMORIA SEMÁNTICA EN RUST)
  qdrant_db:
    image: qdrant/qdrant:latest
    container_name: agnux_qdrant_db
    ports:
      - "6333:6333"  # Puerto HTTP para el cliente de FastAPI
      - "6334:6334"  # Puerto gRPC para máxima velocidad de transferencia
    volumes:
      - ./qdrant_storage:/qdrant/storage  # 💾 Persistencia de rostros, huellas de voz y tools en el host
    networks:
      - agnux_net
    restart: unless-stopped



  # 💻 INTERFAZ GRAFICA FRONTEND: CONSOLA CYBERPUNK INMERSIVA (ANGULAR)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.front
    container_name: agnux_frontend_dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Volumen anónimo para node_modules, evita que choquen las arquitecturas del host y el contenedor
    networks:
      - agnux_net
    restart: unless-stopped

  # 🌐 REVERSE PROXY: NGINX (ENRUTADOR HACIA FRONTEND Y BACKEND)
  agnux_proxy:
    image: nginx:alpine
    container_name: agnux_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - agnux_net
    depends_on:
      - backend
      - frontend
    restart: always

networks:
  agnux_net:
    driver: bridge
    name: agnux_internal_network