[pytest]
minversion = 7.0
addopts = -v --strict-markers --tb=short --disable-warnings
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    functional: mark test as a functional test
    integration: mark test as an integration test
    smoke: mark test as a smoke test
    slow: mark test as slow running
    unit: mark test as a unit test
