import os
import json
import uuid
import logging
import asyncio
from datetime import datetime
from fastapi import FastAPI, HTTPException, UploadFile, File, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import httpx

from qdrant_client import AsyncQdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

from kernel_bus import manager

# =====================================================================
# 1. CONFIGURACIÓN INICIAL Y DEPENDENCIAS
# =====================================================================
# Configuración del logger para volcar telemetría limpia en la consola
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger("AGNUX-CORE")

QDRANT_HOST = os.getenv("QDRANT_HOST", "http://qdrant_db:6333")
qdrant_client = AsyncQdrantClient(url=QDRANT_HOST)

app = FastAPI(title="AGNUX OS Core API", version="2.0.0", redirect_slashes=True)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DYNAMIC_DIR = os.path.join(BASE_DIR, "dynamic_tools")
os.makedirs(DYNAMIC_DIR, exist_ok=True)
if not os.path.exists(os.path.join(DYNAMIC_DIR, "__init__.py")):
    with open(os.path.join(DYNAMIC_DIR, "__init__.py"), "w") as f: f.write("")

# Simulación de extracción matemática
def simular_vector_rostro() -> list[float]:
    import random
    return [random.uniform(-1.0, 1.0) for _ in range(128)]

def simular_vector_texto(texto: str) -> list[float]:
    import random
    return [random.uniform(-1.0, 1.0) for _ in range(768)]

# =====================================================================
# ESQUEMAS DE PYDANTIC (Modelos de Datos)
# =====================================================================
class TaskbarPrompt(BaseModel):
    prompt: str
    user_id: str
    terminal_id: str

class EnrolmentPayload(BaseModel):
    enrolment_id: str
    nombre_usuario: str

class LinkTerminalPayload(BaseModel):
    terminal_id: str
    user_id: str

# =====================================================================
# 2. MATRICES DE MEMORIA GLOBAL (RAM KERNEL)
# =====================================================================
# Matriz principal segmentada en núcleo y contenedores de usuarios
CACHE_VECTORS = {
    "sistema": {},
    "usuarios": {}
}

# Semáforo FIFO asíncrono para evitar saturar el bus de inferencia
OLLAMA_BUS_LOCK = asyncio.Lock()

# Volátil para enrolamiento de rostros no registrados
TEMPORARY_FACE_VECTORS = {}

# Mapeo de terminales físicas (monitores sin cámara esperando al celular)
TERMINAL_SESSIONS = {}

COLECCION_FACIAL = "perfiles_faciales"
COLECCION_MEMORIA = "agnux_kernel_memory"

@app.on_event("startup")
async def inicializar_sistema():
    logger.info("⚡ [KERNEL BOOT] Inicializando servicios base de memoria persistente...")
    try:
        collections_response = await qdrant_client.get_collections()
        collection_names = [col.name for col in collections_response.collections]
        
        if COLECCION_FACIAL not in collection_names:
            logger.info(f"🧠 [QDRANT] Creando colección '{COLECCION_FACIAL}' (128d, COSINE)...")
            await qdrant_client.create_collection(
                collection_name=COLECCION_FACIAL,
                vectors_config=VectorParams(size=128, distance=Distance.COSINE),
            )
            
        if COLECCION_MEMORIA not in collection_names:
            logger.info(f"🧠 [QDRANT] Creando colección '{COLECCION_MEMORIA}' (768d, COSINE)...")
            await qdrant_client.create_collection(
                collection_name=COLECCION_MEMORIA,
                vectors_config=VectorParams(size=768, distance=Distance.COSINE),
            )
    except Exception as e:
        logger.error(f"❌ [QDRANT] Falla al inicializar bus vectorial: {e}")

# =====================================================================
# FUNCIONES AUXILIARES FÍSICAS Y AUTOGÉNESIS
# =====================================================================
async def autogenerar_nueva_tool(nombre_funcion: str, codigo_python: str, descripcion_docstring: str) -> str:
    nombre_limpio = nombre_funcion.strip().lower().replace(" ", "_").replace("-", "_")
    if nombre_limpio.endswith(".py"): nombre_limpio = nombre_limpio.replace(".py", "")
        
    path_archivo = os.path.join(DYNAMIC_DIR, f"{nombre_limpio}.py")

    codigo_depurado = codigo_python.strip()
    if codigo_depurado.startswith("```"):
        codigo_depurado = codigo_depurado.split("```")[1].replace("python", "", 1).strip()

    plantilla_final = (
        f'""\"\nAuto-generated by AGNUX OS. {descripcion_docstring}\n""\"\n\n'
        f'{codigo_depurado}\n'
    )
    
    try:
        with open(path_archivo, "w", encoding="utf-8") as f: f.write(plantilla_final)
        logger.info(f"💾 [AUTOGÉNESIS] Tool instalada asíncronamente en host: {path_archivo}")
        return f"SUCCESS: '{nombre_limpio}' instalada con éxito."
    except Exception as e:
        return f"ERROR KERNEL: Falla crítica en autogénesis: {e}"

async def ejecutar_herramienta_local(nombre: str, argumentos: dict = None, terminal_id: str = None, user_id: str = None) -> str:
    logger.info(f"🔌 [EJECUTOR] Invocando subproceso host: '{nombre}'")
    if argumentos is None: argumentos = {}
    
    # Inyectamos contexto de sistema en los argumentos para que las herramientas generadas
    # puedan acceder a la terminal_id y user_id mediante kwargs
    if terminal_id: argumentos["__terminal_id"] = terminal_id
    if user_id: argumentos["__user_id"] = user_id
    
    if nombre == "autogenerar_nueva_tool":
        return await autogenerar_nueva_tool(**argumentos)
        
    try:
        if os.path.exists(DYNAMIC_DIR):
            import importlib
            for archivo in os.listdir(DYNAMIC_DIR):
                if archivo == f"{nombre}.py":
                    modulo = importlib.import_module(f"dynamic_tools.{nombre}")
                    importlib.reload(modulo)
                    funcion_dinamica = getattr(modulo, nombre)
                    resultado = funcion_dinamica(**argumentos) if argumentos else funcion_dinamica()
                    return str(resultado)
    except Exception as e:
        return f"❌ Falla en herramienta '{nombre}': {e}"
        
    return f"Herramienta '{nombre}' no encontrada en el núcleo."

# =====================================================================
# 3. ENDPOINT CENTRAL DE INTENCIONES CON STREAMING AG-UI
# =====================================================================
@app.websocket("/api/system/notifications/ws/{terminal_id}/{user_id}")
async def websocket_notifications(websocket: WebSocket, terminal_id: str, user_id: str):
    await manager.connect(websocket, terminal_id, user_id)
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        manager.disconnect(terminal_id, user_id)
@app.post("/api/system/intent")
async def procesar_intencion_global(payload: TaskbarPrompt):
    async def generador_eventos():
        try:
            # Verificación del semáforo FIFO
            if OLLAMA_BUS_LOCK.locked():
                yield json.dumps({"event": "QUEUE_WAIT", "message": "Servidor ocupado. Solicitud en cola de espera en el Kernel..."}) + "\n"
    
            # Adquiriendo candado de concurrencia
            async with OLLAMA_BUS_LOCK:
                base_host = os.getenv('OLLAMA_HOST', 'http://10.10.0.48:11434').rstrip("/")
                url_ollama_universal = f"{base_host}/api/generate"
                modelo_activo = os.getenv('AGNUX_ACTIVE_MODEL', 'ministral-es:latest')
    
                yield json.dumps({"event": "ROUTER_START", "message": "Inicializando Router Semántico en Memoria..."}) + "\n"
    
                # Fusión virtual jerárquica con normalización de ID
                id_normalizado = payload.user_id.replace("_", "-")
                tools_privadas = CACHE_VECTORS["usuarios"].get(id_normalizado, {})
                tools_disponibles = {**CACHE_VECTORS["sistema"], **tools_privadas}
    
                vector_usuario = simular_vector_texto(payload.prompt)
                filtered_tools = []
    
                # Router Semántico y emisión geométrica en tiempo real
                for nombre_tool, data in tools_disponibles.items():
                    score = 0.8 # TODO futuro: utilizar similitud de cosenos real aquí con SentenceTransformers
                    yield json.dumps({"event": "ROUTER_SCORE", "tool": nombre_tool, "score": score}) + "\n"
    
                    # Umbral de corte calibrado para ministral:latest
                    if score > 0.42:
                        filtered_tools.append(data["schema"])
    
                if not filtered_tools:
                    filtered_tools.append({
                        "name": "autogenerar_nueva_tool",
                        "description": "Se activa para programar una nueva herramienta",
                        "parameters": {
                            "type": "object",
                            "properties": {
                                "nombre_funcion": {"type": "string"},
                                "codigo_python": {"type": "string"},
                                "descripcion_docstring": {"type": "string"}
                            },
                            "required": ["nombre_funcion", "codigo_python", "descripcion_docstring"]
                        }
                    })
    
                openai_tools = [{"type": "function", "function": t} for t in filtered_tools] if filtered_tools else None
    
                SYSTEM_PROMPT = """Sos el kernel principal de AGNUX OS. Responde siempre corto y ejecutivo.
    
    ## 2.1 REGLAS ESTRICTAS DE NOMENCLATURA DE RED (ESTÁNDAR DE KERNEL LINUX Y DNS)
    - Está TAXATIVAMENTE PROHIBIDO el uso de guiones bajos ('_') en cualquier identificador de usuario, nombre de terminal, o nombre de herramienta dinámica que interactúe con el host. El guión bajo rompe la sintaxis de interfaces de WireGuard y las especificaciones de Hostnames de internet (RFC 1035).
    - Todo identificador debe normalizarse utilizando única y exclusivamente guiones medios ('-') o formato alfanumérico plano en minúsculas (ejemplo correcto: 'user-cristian', 'global-calculadora', 'term-desktop-101').
    - Si vas a autogenerar código en caliente para una nueva herramienta, el archivo físico en disco y su registro semántico deben usar guiones medios (ej. 'global-control-bomba.py').

    ## NOTIFICACIONES PUSH (HYPERISLAND)
    Si estás autogenerando una herramienta y necesitas notificar al usuario, puedes usar WebSockets puros.
    Importa de forma asíncrona: `from kernel_bus import notificar_frontend` y ejecuta:
    `await notificar_frontend(kwargs.get("__terminal_id"), kwargs.get("__user_id"), "Mensaje", "notif")`
    """
    
                payload_ollama = {
                    "model": modelo_activo,
                    "prompt": f"{SYSTEM_PROMPT}\n\nUser: {payload.prompt}",
                    "stream": True
                }
                # Nota: El endpoint /api/generate es de texto plano y no procesa 'tools' de forma nativa.
    
                tool_call_detected = None
                argumentos_acumulados = ""
    
                try:
                    # Streaming multiplexado al bus Ollama
                    async with httpx.AsyncClient() as client:
                        async with client.stream("POST", url_ollama_universal, json=payload_ollama, timeout=60.0) as response:
                            if response.status_code != 200:
                                yield json.dumps({"event": "ERROR", "message": f"Bus Inferencia Caído. HTTP {response.status_code}"}) + "\n"
                                return
    
                            # 1. Consolidamos el texto que nos mandó Ministral
                            respuesta_completa = ""
                            async for line in response.aiter_lines():
                                if line:
                                    try:
                                        data = json.loads(line)
                                        token = data.get("response", "")
                                        if token:
                                            respuesta_completa += token
                                            # Emitimos bajo el protocolo AG-UI para la barra verde
                                            yield f"event: TOKEN\ndata: {json.dumps(token)}\n\n"
                                    except Exception:
                                        continue
    
                            # 2. 🧠 EL CIRCUITO QUE SE HABÍA ROTO: Evaluación de acción
                            logger.info(f"🧠 [KERNEL AGENTE] Evaluando acción para la respuesta: {respuesta_completa}")
                            
                            import re
                            bloque_python = re.search(r'```python\s*(.*?)\s*```', respuesta_completa, re.DOTALL)
                            match_nombre = re.search(r'`([^`]+)\.py`', respuesta_completa) or re.search(r'\*\*Nombre sugerido:\*\*\s*`([^`]+)`', respuesta_completa)

                            if bloque_python and match_nombre:
                                tool_call_detected = "autogenerar_nueva_tool"
                                nombre_func = match_nombre.group(1).replace(".py", "")
                                argumentos_acumulados = json.dumps({
                                    "nombre_funcion": nombre_func,
                                    "codigo_python": bloque_python.group(1),
                                    "descripcion_docstring": "Tool generada en tiempo de ejecución"
                                })
                                logger.info(f"⚙️ [KERNEL AGENTE] Tool heurística detectada en stream: {nombre_func}")
                                # No retornamos. El flujo continuará abajo para invocar 'ejecutar_herramienta_local'.
                            else:
                                # Si la IA determinó que es una respuesta directa o texto para el operador,
                                # el backend es el responsable de ordenarle a Angular que dibuje la ventana flotante
                                payload_ventana = {
                                    "window_id": "agnux-ai-window",
                                    "title": "🧠 AGNUX OS Core - Ministral IA",
                                    "content": respuesta_completa,
                                    "type": "terminal"
                                }
        
                                # Emitimos el evento de infraestructura nativo que Angular espera para spawnear ventanas
                                yield f"event: CREATE_WINDOW\ndata: {json.dumps(payload_ventana, ensure_ascii=False)}\n\n"
        
                                # 🔥 EL FIX CRUCIAL: Forzamos la destrucción del generador asíncrono y cerramos el socket HTTP
                                logger.info("🔌 [KERNEL AGENTE] Tarea cumplida. Liberando canal de intent de forma inmediata.")
                                return
    
                except Exception as e:
                    yield json.dumps({"event": "ERROR", "message": f"Ollama Stream Network Error: {e}"}) + "\n"
                    return
    
                if tool_call_detected:
                    yield json.dumps({"event": "TOOL_EXECUTE", "message": f"Ejecución solicitada a Kernel: {tool_call_detected}"}) + "\n"
                    try:
                        args = json.loads(argumentos_acumulados) if argumentos_acumulados else {}
                        resultado_fierros = await ejecutar_herramienta_local(
                            tool_call_detected, 
                            args, 
                            terminal_id=payload.terminal_id, 
                            user_id=payload.user_id
                        )
    
                        yield json.dumps({"event": "TOOL_RESULT", "data": resultado_fierros}) + "\n"
    
                        # Criterio de promoción: ¿es una tool de sistema u over-ride global?
                        if tool_call_detected == "autogenerar_nueva_tool" and args.get("nombre_funcion", "").startswith("global_"):
                            nombre_func = args["nombre_funcion"]
                            CACHE_VECTORS["sistema"][nombre_func] = {
                                "vector": simular_vector_texto(args.get("descripcion_docstring", "")),
                                "schema": {
                                    "name": nombre_func,
                                    "description": args.get("descripcion_docstring", ""),
                                    "parameters": {"type": "object", "properties": {}}
                                }
                            }
                            logger.info(f"🌐 [RAM KERNEL] Escalada de privilegios: Herramienta '{nombre_func}' promovida a GLOBAL.")
    
                    except Exception as e:
                        yield json.dumps({"event": "ERROR", "message": f"Falla física en tool_call: {e}"}) + "\n"
        finally:
            logger.info("🔌 [KERNEL AGENTE] Limpiando recursos del generador asíncrono.")

    return StreamingResponse(generador_eventos(), media_type="text/event-stream")

# =====================================================================
# 4. ENDPOINTS DE BYPASS BIOMÉTRICO Y LOGIN REMOTO
# =====================================================================
@app.get("/api/auth/terminal-stream/{terminal_id}")
async def terminal_stream(terminal_id: str):
    # Reserva inicial del socket
    TERMINAL_SESSIONS[terminal_id] = {"status": "pending", "user_id": None}
    logger.info(f"📡 [TERMINAL] Sesión abierta y esperando autenticación remota para: {terminal_id}")
    
    async def sse_bypass():
        try:
            while True:
                estado = TERMINAL_SESSIONS.get(terminal_id)
                if estado and estado.get("status") == "approved":
                    userid = estado.get("user-id") or estado.get("user_id") # Tolerancia de parseo interno
                    logger.info(f"✅ [TERMINAL] Aprobación detectada. Liberando terminal para: {userid}")
                    yield f"event: AUTH-SUCCESS\ndata: {json.dumps({'userId': userid})}\n\n"
                    await asyncio.sleep(1.5) # ⏳ Delay de cortesía para el buffer de red de Chrome
                    break
                
                # Mantenimiento del túnel SSE abierto
                yield f"event: HEARTBEAT\ndata: {json.dumps({'status': 'keep-alive'})}\n\n"
                await asyncio.sleep(1.0)
        finally:
            # Destruye el socket local de la tabla
            TERMINAL_SESSIONS.pop(terminal_id, None)
            
    return StreamingResponse(sse_bypass(), media_type="text/event-stream")

@app.post("/api/auth/terminal-authorize")
@app.post("/api/auth/terminal-authorize/")
async def terminal_authorize(payload: LinkTerminalPayload):
    # Normalización forzada de red (RFC 1035)
    id_red = payload.user_id.replace("_", "-")
    
    # Llamado por el móvil bajo VPN WireGuard
    if payload.terminal_id in TERMINAL_SESSIONS:
        try:
            logger.info(f"🔎 [KERNEL QDRANT] Buscando perfil para operador: {id_red}")
            # Intentamos buscar el vector o datos del usuario en la BD
            # Si la base está vacía, apagada o el user_id no figura, saltará la excepción
            await qdrant_client.scroll(
                collection_name=COLECCION_FACIAL,
                limit=1
            )
            rol_operador = "admin"
        except Exception as db_error:
            # 🚨 Si la DB falla o el usuario es nuevo, ACTIVAMOS EL MODO TOLERANTE:
            logger.warn(f"⚠️ [KERNEL] Operador '{id_red}' no encontrado en Qdrant o DB vacía. Activando perfil de contingencia local.")
            rol_operador = "admin-provisional"
            
        # Forzar la conmutación de estado a approved con tolerancia
        TERMINAL_SESSIONS[payload.terminal_id] = {
            "status": "approved",
            "user_id": id_red,
            "role": rol_operador
        }
        
        # Evitar fallos de referencia en Router inicializando el slot de este usuario
        if id_red not in CACHE_VECTORS["usuarios"]:
            CACHE_VECTORS["usuarios"][id_red] = {}
            logger.info(f"🗂️ [RAM KERNEL] Slot privado creado al vuelo para: {id_red}")
            
        logger.info(f"🔓 [BYPASS VPN] Terminal {payload.terminal_id} desbloqueada por el celular de: {id_red}")
        return {"status": "success"}
    else:
        raise HTTPException(status_code=404, detail="Terminal remota inactiva o ID inválido")

@app.post("/api/auth/facial-login")
@app.post("/api/auth/facial-login/")
async def facial_login(file: UploadFile = File(...)):
    try:
        contenido = await file.read()
        vector_rostro = simular_vector_rostro()
        
        search_result = None
        try:
            search_result = await qdrant_client.query_points(
                collection_name=COLECCION_FACIAL,
                query=vector_rostro,
                limit=1
            )
        except Exception as db_err:
            logger.warn(f"⚠️ [KERNEL QDRANT] No se pudo leer el vector de Qdrant ({str(db_err)}). Continuando en modo local seguro.")
        
        if search_result and search_result.points and search_result.points[0].score > 0.85: 
            user_id = search_result.points[0].payload.get("user_id")
            return {"status": "authenticated", "user_id": user_id}
        else:
            # Retiene el vector temporal e insta a aprobar desde app
            enrolment_id = str(uuid.uuid4())
            TEMPORARY_FACE_VECTORS[enrolment_id] = vector_rostro
            logger.info(f"📸 [BIOMETRÍA] Rostro DESCONOCIDO detectado. Emisión de EnrolmentID: {enrolment_id}")
            return {"status": "unknown_face", "enrolment_id": enrolment_id}
            
    except Exception as e:
        logger.error(f"Falla en bus de biometría facial: {e}")
        raise HTTPException(status_code=500, detail="Fallo catastrófico en análisis biométrico")

@app.post("/api/auth/register-profile")
@app.post("/api/auth/register-profile/")
async def register_profile(payload: EnrolmentPayload):
    if payload.enrolment_id not in TEMPORARY_FACE_VECTORS:
        raise HTTPException(status_code=400, detail="Error de seguridad: ID de enrolamiento expirado o ficticio")
        
    vector_rostro = TEMPORARY_FACE_VECTORS[payload.enrolment_id]
    user_id_limpio = "user-" + payload.nombre_usuario.strip().lower().replace(" ", "-").replace("_", "-")
    
    punto_id = int(datetime.now().timestamp() * 1000)
    punto = PointStruct(
        id=punto_id,
        vector=vector_rostro,
        payload={"user_id": user_id_limpio, "nombre": payload.nombre_usuario}
    )
    
    try:
        # Inserción en memoria permanente de largo plazo
        await qdrant_client.upsert(
            collection_name=COLECCION_FACIAL,
            points=[punto]
        )
        
        # Inserción asíncrona segura en RAM volátil del Kernel
        if user_id_limpio not in CACHE_VECTORS["usuarios"]:
            CACHE_VECTORS["usuarios"][user_id_limpio] = {}
            
        # Destruir evidencia temporal
        del TEMPORARY_FACE_VECTORS[payload.enrolment_id]
        logger.info(f"👤 [IDENTITY KERNEL] Nuevo perfil creado y blindado en RAM/Qdrant: {user_id_limpio}")
        
        return {"status": "profile_created", "user_id": user_id_limpio}
    except Exception as e:
        logger.error(f"Falla en registro profundo: {e}")
        raise HTTPException(status_code=500, detail="Error transaccional en persistencia de Qdrant DB")